### ISSUE TITLE
Section 4 -> The method getCustomerId() is undefined for the type Customer

### ISSUE THREAD

**Issue by AlexandruPisica** [eazybytes/microservices-with-spring-sectionwise-code#3]
Hi,

In Section 4, Chapter 17 -> AccountsController.java fails to compile this line:

Accounts accounts = accountsRepository.findByCustomerId(customer.getCustomerId());

The error is: The method getCustomerId() is undefined for the type Customer

Please advise,
Alex

**Comment by eazybytes** [comment]
Seems you have an issue with the Lombok annotations. Could you please go to https://projectlombok.org/ and follow the instruction mentioned for installation based on the IDE that you use. Please restart the IDE and do a complete maven build.

Also please make sure to enable Annotations processing inside your IDE.

Hope this steps solve your problem. Otherwise please remove Lombok annotations and use the direct getter & setter methods inside your model classes.

Thanks

![2022-09-15_15-30-42-a11901678b568dc54d3d4a10d0a36e76](https://github.com/eazybytes/microservices-with-spring-sectionwise-code/assets/79041235/a6ba0bf3-f97f-4c84-81b6-f6978c139d1a)
![2022-09-15_15-30-43-8588cd342d24caab4bba731f131400cb](https://github.com/eazybytes/microservices-with-spring-sectionwise-code/assets/79041235/da3f1f29-cdfb-4977-8d14-521866a51b74)
